name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.pymesmelipilla.cl
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        protocol: ftps
        server-dir: 
        local-dir: Fase 2/Evidencias Proyecto/Evidencias de sistema/sercotec-app/
        exclude: |
          **/.env*
          **/.git*
          **/.git*/**
          **/.github*/**
          **/.github*/*
